# PROBLEMA 1
run-problem-1:
	java -cp ./problema1/classes Function

compile-problem-1:
	javac -d ./problema1/classes problema1/Function.java

# PROBLEMA 2

run-problem-2:
	java -cp ./problema2/classes Comparision

compile-problem-2:
	javac -d ./problema2/classes problema2/QuickSort/QuickSort.java problema2/QuickSort/QuickSortThreading.java problema2/Comparision.java
